package com.fpm.crud;


import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class SystemXDesign extends CssLayout {

    protected TextField systemXName;
    protected TextField p1;
    protected TextField p2;
    protected TextField p3;
    protected ComboBox ata;
    protected CategoryField category;
    protected Button save;
    protected Button cancel;
    protected Button delete;

    public SystemXDesign() {
        Design.read(this);
    }
}
